### ISSUE TITLE
Provide README

### ISSUE THREAD

**Issue by adibaba** [projekt-opal/web-service#2]
A README file is required. It should contain a description containing:

- How to build/start the project (e.g. maven build)
- How to set configuration values (required in application.yml)  
  Eventually provide a default configuration file with empty values

Example: https://github.com/projekt-opal/opaldata/

**Comment by adibaba** [comment]
For instance, the webservice can be provided by 3 files:

Dockerfile
```
FROM maven:3-jdk-8

RUN wget https://github.com/projekt-opal/opal-webservices/archive/developer.zip && unzip developer.zip && cd opal-webservices-developer && mvn clean package

CMD cd opal-webservices-developer && java -jar target/opal-webservices-1.0.0.0.jar
```

docker-compose.yml
```
# OPAL data Webservices
# 
# Repository:
# https://github.com/projekt-opal/opaldata

version: '3.2'

services:
  opal-webservices:
    environment:
      - OPAL_TRIPLESTORE_URL=${OPAL_TRIPLESTORE_URL}
      - OPAL_TRIPLESTORE_USERNAME=${OPAL_TRIPLESTORE_USERNAME}
      - OPAL_TRIPLESTORE_PASSWORD=${OPAL_TRIPLESTORE_PASSWORD}
    ports:
      - 8081:8081
    build: .
    volumes:
      - logwebservices:/var/log/opal/
volumes:
  logwebservices:
  eslog:
```

.env
```
OPAL_TRIPLESTORE_URL=XXX
OPAL_TRIPLESTORE_USERNAME=XXX
OPAL_TRIPLESTORE_PASSWORD=XXX
```
